version: '3.1'

services:
  product-inventory-db:
    image: postgres:12.1
    restart: "no"
    ports:
    - 5432:5432
    networks:
      - net
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: productinventory
networks:
  net: